version: "3.7"

services:
  golang-rest-docker:
    container_name: golang-rest-docker
    image: golang-rest-docker
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"
    networks:
      - main_network
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-sample_root_pass}
      MYSQL_DATABASE: ${DB_NAME:-sample_db}
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - main_network
    restart: unless-stopped

networks:
  main_network:
    name: main_network
    driver: bridge

volumes:
  mysql-db:  